# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _RoCo2
else:
    import _RoCo2

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class PingPacket(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    time = property(_RoCo2.PingPacket_time_get, _RoCo2.PingPacket_time_set)

    def __init__(self):
        _RoCo2.PingPacket_swiginit(self, _RoCo2.new_PingPacket())
    __swig_destroy__ = _RoCo2.delete_PingPacket

# Register PingPacket in _RoCo2:
_RoCo2.PingPacket_swigregister(PingPacket)

class ConnectPacket(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    name = property(_RoCo2.ConnectPacket_name_get, _RoCo2.ConnectPacket_name_set)

    def __init__(self):
        _RoCo2.ConnectPacket_swiginit(self, _RoCo2.new_ConnectPacket())
    __swig_destroy__ = _RoCo2.delete_ConnectPacket

# Register ConnectPacket in _RoCo2:
_RoCo2.ConnectPacket_swigregister(ConnectPacket)

class DisconnectPacket(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _RoCo2.DisconnectPacket_swiginit(self, _RoCo2.new_DisconnectPacket())
    __swig_destroy__ = _RoCo2.delete_DisconnectPacket

# Register DisconnectPacket in _RoCo2:
_RoCo2.DisconnectPacket_swigregister(DisconnectPacket)

class RequestPacket(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    uuid = property(_RoCo2.RequestPacket_uuid_get, _RoCo2.RequestPacket_uuid_set)
    action_id = property(_RoCo2.RequestPacket_action_id_get, _RoCo2.RequestPacket_action_id_set)
    target_id = property(_RoCo2.RequestPacket_target_id_get, _RoCo2.RequestPacket_target_id_set)
    payload = property(_RoCo2.RequestPacket_payload_get, _RoCo2.RequestPacket_payload_set)

    def __init__(self):
        _RoCo2.RequestPacket_swiginit(self, _RoCo2.new_RequestPacket())
    __swig_destroy__ = _RoCo2.delete_RequestPacket

# Register RequestPacket in _RoCo2:
_RoCo2.RequestPacket_swigregister(RequestPacket)

class AcknowledgePacket(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    uuid = property(_RoCo2.AcknowledgePacket_uuid_get, _RoCo2.AcknowledgePacket_uuid_set)
    result = property(_RoCo2.AcknowledgePacket_result_get, _RoCo2.AcknowledgePacket_result_set)

    def __init__(self):
        _RoCo2.AcknowledgePacket_swiginit(self, _RoCo2.new_AcknowledgePacket())
    __swig_destroy__ = _RoCo2.delete_AcknowledgePacket

# Register AcknowledgePacket in _RoCo2:
_RoCo2.AcknowledgePacket_swigregister(AcknowledgePacket)

class ResponsePacket(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    uuid = property(_RoCo2.ResponsePacket_uuid_get, _RoCo2.ResponsePacket_uuid_set)
    action_id = property(_RoCo2.ResponsePacket_action_id_get, _RoCo2.ResponsePacket_action_id_set)
    target_id = property(_RoCo2.ResponsePacket_target_id_get, _RoCo2.ResponsePacket_target_id_set)
    payload = property(_RoCo2.ResponsePacket_payload_get, _RoCo2.ResponsePacket_payload_set)

    def __init__(self):
        _RoCo2.ResponsePacket_swiginit(self, _RoCo2.new_ResponsePacket())
    __swig_destroy__ = _RoCo2.delete_ResponsePacket

# Register ResponsePacket in _RoCo2:
_RoCo2.ResponsePacket_swigregister(ResponsePacket)

class ProgressPacket(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    uuid = property(_RoCo2.ProgressPacket_uuid_get, _RoCo2.ProgressPacket_uuid_set)
    progress = property(_RoCo2.ProgressPacket_progress_get, _RoCo2.ProgressPacket_progress_set)

    def __init__(self):
        _RoCo2.ProgressPacket_swiginit(self, _RoCo2.new_ProgressPacket())
    __swig_destroy__ = _RoCo2.delete_ProgressPacket

# Register ProgressPacket in _RoCo2:
_RoCo2.ProgressPacket_swigregister(ProgressPacket)

class DataPacket(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    data = property(_RoCo2.DataPacket_data_get, _RoCo2.DataPacket_data_set)

    def __init__(self):
        _RoCo2.DataPacket_swiginit(self, _RoCo2.new_DataPacket())
    __swig_destroy__ = _RoCo2.delete_DataPacket

# Register DataPacket in _RoCo2:
_RoCo2.DataPacket_swigregister(DataPacket)

class MessagePacket(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    message = property(_RoCo2.MessagePacket_message_get, _RoCo2.MessagePacket_message_set)

    def __init__(self):
        _RoCo2.MessagePacket_swiginit(self, _RoCo2.new_MessagePacket())
    __swig_destroy__ = _RoCo2.delete_MessagePacket

# Register MessagePacket in _RoCo2:
_RoCo2.MessagePacket_swigregister(MessagePacket)

class ErrorPacket(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    error_id = property(_RoCo2.ErrorPacket_error_id_get, _RoCo2.ErrorPacket_error_id_set)

    def __init__(self):
        _RoCo2.ErrorPacket_swiginit(self, _RoCo2.new_ErrorPacket())
    __swig_destroy__ = _RoCo2.delete_ErrorPacket

# Register ErrorPacket in _RoCo2:
_RoCo2.ErrorPacket_swigregister(ErrorPacket)

class IODriver(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _RoCo2.delete_IODriver

    def receive(self, receiver: "std::function< void (uint8_t,uint8_t *,uint32_t) > const &") -> "void":
        return _RoCo2.IODriver_receive(self, receiver)

    def transmit(self, buffer: "uint8_t *", length: "uint32_t") -> "void":
        return _RoCo2.IODriver_transmit(self, buffer, length)

# Register IODriver in _RoCo2:
_RoCo2.IODriver_swigregister(IODriver)

class NetworkClientIO(IODriver):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, address: "char const *", port: "uint16_t"):
        _RoCo2.NetworkClientIO_swiginit(self, _RoCo2.new_NetworkClientIO(address, port))
    __swig_destroy__ = _RoCo2.delete_NetworkClientIO

    def connectClient(self) -> "int8_t":
        return _RoCo2.NetworkClientIO_connectClient(self)

    def disconnectClient(self) -> "void":
        return _RoCo2.NetworkClientIO_disconnectClient(self)

    def receive(self, receiver: "std::function< void (uint8_t,uint8_t *,uint32_t) > const &") -> "void":
        return _RoCo2.NetworkClientIO_receive(self, receiver)

    def transmit(self, buffer: "uint8_t *", length: "uint32_t") -> "void":
        return _RoCo2.NetworkClientIO_transmit(self, buffer, length)

# Register NetworkClientIO in _RoCo2:
_RoCo2.NetworkClientIO_swigregister(NetworkClientIO)

class PacketDefinition(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    id = property(_RoCo2.PacketDefinition_id_get, _RoCo2.PacketDefinition_id_set)
    size = property(_RoCo2.PacketDefinition_size_get, _RoCo2.PacketDefinition_size_set)
    hash = property(_RoCo2.PacketDefinition_hash_get, _RoCo2.PacketDefinition_hash_set)

    def __init__(self):
        _RoCo2.PacketDefinition_swiginit(self, _RoCo2.new_PacketDefinition())
    __swig_destroy__ = _RoCo2.delete_PacketDefinition

# Register PacketDefinition in _RoCo2:
_RoCo2.PacketDefinition_swigregister(PacketDefinition)
cvar = _RoCo2.cvar
null_type = cvar.null_type

class MessageBus(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _RoCo2.delete_MessageBus

    def definePingPacket(self, identifier: "uint8_t") -> "bool":
        return _RoCo2.MessageBus_definePingPacket(self, identifier)

    def handlePingPacket(self, handler: "void (*)(uint8_t,PingPacket *)") -> "bool":
        return _RoCo2.MessageBus_handlePingPacket(self, handler)

    def forwardPingPacket(self, bus: "MessageBus") -> "bool":
        return _RoCo2.MessageBus_forwardPingPacket(self, bus)

    def sendPingPacket(self, message: "PingPacket") -> "bool":
        return _RoCo2.MessageBus_sendPingPacket(self, message)

    def defineConnectPacket(self, identifier: "uint8_t") -> "bool":
        return _RoCo2.MessageBus_defineConnectPacket(self, identifier)

    def handleConnectPacket(self, handler: "void (*)(uint8_t,ConnectPacket *)") -> "bool":
        return _RoCo2.MessageBus_handleConnectPacket(self, handler)

    def forwardConnectPacket(self, bus: "MessageBus") -> "bool":
        return _RoCo2.MessageBus_forwardConnectPacket(self, bus)

    def sendConnectPacket(self, message: "ConnectPacket") -> "bool":
        return _RoCo2.MessageBus_sendConnectPacket(self, message)

    def defineDisconnectPacket(self, identifier: "uint8_t") -> "bool":
        return _RoCo2.MessageBus_defineDisconnectPacket(self, identifier)

    def handleDisconnectPacket(self, handler: "void (*)(uint8_t,DisconnectPacket *)") -> "bool":
        return _RoCo2.MessageBus_handleDisconnectPacket(self, handler)

    def forwardDisconnectPacket(self, bus: "MessageBus") -> "bool":
        return _RoCo2.MessageBus_forwardDisconnectPacket(self, bus)

    def sendDisconnectPacket(self, message: "DisconnectPacket") -> "bool":
        return _RoCo2.MessageBus_sendDisconnectPacket(self, message)

    def defineRequestPacket(self, identifier: "uint8_t") -> "bool":
        return _RoCo2.MessageBus_defineRequestPacket(self, identifier)

    def handleRequestPacket(self, handler: "void (*)(uint8_t,RequestPacket *)") -> "bool":
        return _RoCo2.MessageBus_handleRequestPacket(self, handler)

    def forwardRequestPacket(self, bus: "MessageBus") -> "bool":
        return _RoCo2.MessageBus_forwardRequestPacket(self, bus)

    def sendRequestPacket(self, message: "RequestPacket") -> "bool":
        return _RoCo2.MessageBus_sendRequestPacket(self, message)

    def defineAcknowledgePacket(self, identifier: "uint8_t") -> "bool":
        return _RoCo2.MessageBus_defineAcknowledgePacket(self, identifier)

    def handleAcknowledgePacket(self, handler: "void (*)(uint8_t,AcknowledgePacket *)") -> "bool":
        return _RoCo2.MessageBus_handleAcknowledgePacket(self, handler)

    def forwardAcknowledgePacket(self, bus: "MessageBus") -> "bool":
        return _RoCo2.MessageBus_forwardAcknowledgePacket(self, bus)

    def sendAcknowledgePacket(self, message: "AcknowledgePacket") -> "bool":
        return _RoCo2.MessageBus_sendAcknowledgePacket(self, message)

    def defineResponsePacket(self, identifier: "uint8_t") -> "bool":
        return _RoCo2.MessageBus_defineResponsePacket(self, identifier)

    def handleResponsePacket(self, handler: "void (*)(uint8_t,ResponsePacket *)") -> "bool":
        return _RoCo2.MessageBus_handleResponsePacket(self, handler)

    def forwardResponsePacket(self, bus: "MessageBus") -> "bool":
        return _RoCo2.MessageBus_forwardResponsePacket(self, bus)

    def sendResponsePacket(self, message: "ResponsePacket") -> "bool":
        return _RoCo2.MessageBus_sendResponsePacket(self, message)

    def defineProgressPacket(self, identifier: "uint8_t") -> "bool":
        return _RoCo2.MessageBus_defineProgressPacket(self, identifier)

    def handleProgressPacket(self, handler: "void (*)(uint8_t,ProgressPacket *)") -> "bool":
        return _RoCo2.MessageBus_handleProgressPacket(self, handler)

    def forwardProgressPacket(self, bus: "MessageBus") -> "bool":
        return _RoCo2.MessageBus_forwardProgressPacket(self, bus)

    def sendProgressPacket(self, message: "ProgressPacket") -> "bool":
        return _RoCo2.MessageBus_sendProgressPacket(self, message)

    def defineDataPacket(self, identifier: "uint8_t") -> "bool":
        return _RoCo2.MessageBus_defineDataPacket(self, identifier)

    def handleDataPacket(self, handler: "void (*)(uint8_t,DataPacket *)") -> "bool":
        return _RoCo2.MessageBus_handleDataPacket(self, handler)

    def forwardDataPacket(self, bus: "MessageBus") -> "bool":
        return _RoCo2.MessageBus_forwardDataPacket(self, bus)

    def sendDataPacket(self, message: "DataPacket") -> "bool":
        return _RoCo2.MessageBus_sendDataPacket(self, message)

    def defineMessagePacket(self, identifier: "uint8_t") -> "bool":
        return _RoCo2.MessageBus_defineMessagePacket(self, identifier)

    def handleMessagePacket(self, handler: "void (*)(uint8_t,MessagePacket *)") -> "bool":
        return _RoCo2.MessageBus_handleMessagePacket(self, handler)

    def forwardMessagePacket(self, bus: "MessageBus") -> "bool":
        return _RoCo2.MessageBus_forwardMessagePacket(self, bus)

    def sendMessagePacket(self, message: "MessagePacket") -> "bool":
        return _RoCo2.MessageBus_sendMessagePacket(self, message)

    def defineErrorPacket(self, identifier: "uint8_t") -> "bool":
        return _RoCo2.MessageBus_defineErrorPacket(self, identifier)

    def handleErrorPacket(self, handler: "void (*)(uint8_t,ErrorPacket *)") -> "bool":
        return _RoCo2.MessageBus_handleErrorPacket(self, handler)

    def forwardErrorPacket(self, bus: "MessageBus") -> "bool":
        return _RoCo2.MessageBus_forwardErrorPacket(self, bus)

    def sendErrorPacket(self, message: "ErrorPacket") -> "bool":
        return _RoCo2.MessageBus_sendErrorPacket(self, message)

# Register MessageBus in _RoCo2:
_RoCo2.MessageBus_swigregister(MessageBus)

class IOBus(MessageBus):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, driver: "IODriver", buffer: "uint8_t *", length: "uint32_t"):
        _RoCo2.IOBus_swiginit(self, _RoCo2.new_IOBus(driver, buffer, length))
    __swig_destroy__ = _RoCo2.delete_IOBus

# Register IOBus in _RoCo2:
_RoCo2.IOBus_swigregister(IOBus)

NETWORK_FRAME_SIZE = _RoCo2.NETWORK_FRAME_SIZE
class NetworkBus(IOBus):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, driver: "IODriver"):
        _RoCo2.NetworkBus_swiginit(self, _RoCo2.new_NetworkBus(driver))
    __swig_destroy__ = _RoCo2.delete_NetworkBus

# Register NetworkBus in _RoCo2:
_RoCo2.NetworkBus_swigregister(NetworkBus)



